import food from "../components/assets/joseph-gonzalez-zcUgjyqEwe8-unsplash.jpg";
export const storeProducts = [
  {
    id: 1,
    title: "Google Pixel - Black",
    img: food,
    price: 10,
    company: "GOOGLE",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
  {
    id: 2,
    title: "Samsung S7",
    img: food,
    price: 16,
    company: "SAMSUNG",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
  {
    id: 3,
    title: "HTC 10 - Black",
    img: food,
    price: 8,
    company: "htc",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
  {
    id: 4,
    title: "HTC 10 - White",
    img: food,
    price: 18,
    company: "htc",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
  {
    id: 5,
    title: "HTC Desire 626s",
    img: food,
    price: 24,
    company: "htc",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
  {
    id: 6,
    title: "Vintage Iphone",
    img: food,
    price: 17,
    company: "apple",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
  {
    id: 7,
    title: "Iphone 7",
    img: food,
    price: 30,
    company: "apple",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
  {
    id: 8,
    title: "Smashed Iphone",
    img: food,
    price: 2,
    company: "apple",
    info: "piizzaa with extra suace and effect",
    inCart: false,
    count: 0,
    total: 0,
    cutOffPrice: 12,
  },
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: food,
  price: 10,
  company: "google",
  info: "piizzaa with extra suace and effect",
  inCart: false,
  count: 0,
  total: 0,
  cutOffPrice: 12,
};
